# Generated by Django 3.1.4 on 2021-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20210101_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anonymous_grading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_to',
            field=models.ManyToManyField(to='lms.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='display_grades',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('complete/Incomplete', 'Complete/Incomplete'), ('points', 'Points'), ('letter grade', 'Letter Grade'), ('GPA scale', 'GPA Scale'), ('not graded', 'Not Graded')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sub_type',
            field=models.CharField(choices=[('no submission', 'No  Submission'), ('online', 'Online'), ('on paper', 'On Paper'), ('external tool', 'External Tool')], default='no submission', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
