# Generated by Django 3.1.4 on 2021-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20210102_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
