# Generated by Django 3.1.4 on 2021-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20210102_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='onlineoptions',
            field=models.BooleanField(choices=[('text entry', 'Text Entry'), ('website url', 'Website URL'), ('media recordings', 'Media Recordings'), ('file upload', 'File Upload')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_to',
            field=models.ManyToManyField(to='lms.Course'),
        ),
    ]
